version: "3.9"
services:
  mongo1:
    image: mongo:7
    hostname: mongo1
    command: ["mongod","--replSet","rs0","--bind_ip_all"]
    ports: ["27017:27017"]
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1g
  mongo2:
    image: mongo:7
    hostname: mongo2
    command: ["mongod","--replSet","rs0","--bind_ip_all"]
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1g
  mongo3:
    image: mongo:7
    hostname: mongo3
    command: ["mongod","--replSet","rs0","--bind_ip_all"]
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1g
