version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    platform: linux/amd64
    container_name: mssql2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3g
volumes:
  mssqldata:
