version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: "256m"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1.5g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      retries: 5
volumes:
  pgdata:
