version: "3.9"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    command: >
      etcd -name etcd0
      -advertise-client-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2379
    ports: ["2379:2379"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256m

  haproxy:
    image: haproxy:2.9
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports: ["5000:5000", "7000:7000"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256m

  pg01:
    image: ghcr.io/zalando/patroni:3.0
    volumes:
      - ./pg01.yml:/config/patroni.yml:ro
    command: ["patroni", "/config/patroni.yml"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1250m

  pg02:
    image: ghcr.io/zalando/patroni:3.0
    volumes:
      - ./pg02.yml:/config/patroni.yml:ro
    command: ["patroni", "/config/patroni.yml"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1250m

  pg03:
    image: ghcr.io/zalando/patroni:3.0
    volumes:
      - ./pg03.yml:/config/patroni.yml:ro
    command: ["patroni", "/config/patroni.yml"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1250m
